### ISSUE TITLE
Cursor moving to beginning of node after typing an accented character

### ISSUE THREAD

**Issue by Angel-GoMo** [freeplane/docs#92]
[1.10.5-pre05]

After typing an accented character, the accented characters shows OK but the cursor moves to the beginning of the node.

**Comment by macmarrum** [comment]
Thanks for the bug report.
Please note this is a Freeplane documentation project; I'm going to close this issue.

You can create an issue in the main Freeplane project: [bug report](https://github.com/freeplane/freeplane/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

Please list your operating system, the keyboard layout, the steps (key presses) you perform that cause the issue, so that it can be repeated for investigation.
